// <auto-generated />
using System;
using CateringApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CateringApp.Migrations
{
    [DbContext(typeof(MyAppContext))]
    partial class MyAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CateringApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ingredients"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dishes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hardware"
                        });
                });

            modelBuilder.Entity("CateringApp.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("CateringApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Item");

                    b.HasDiscriminator().HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CateringApp.Models.ItemClient", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("ItemId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("ItemClients");
                });

            modelBuilder.Entity("CateringApp.Models.SerialNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HardwareItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HardwareItemId")
                        .IsUnique()
                        .HasFilter("[HardwareItemId] IS NOT NULL");

                    b.ToTable("SerialNumbers");
                });

            modelBuilder.Entity("CateringApp.Models.InventoryItem", b =>
                {
                    b.HasBaseType("CateringApp.Models.Item");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("InventoryItem");
                });

            modelBuilder.Entity("CateringApp.Models.MenuItem", b =>
                {
                    b.HasBaseType("CateringApp.Models.Item");

                    b.Property<int>("CookingMethod")
                        .HasColumnType("int");

                    b.Property<int>("Serves")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MenuItem");
                });

            modelBuilder.Entity("CateringApp.Models.HardwareItem", b =>
                {
                    b.HasBaseType("CateringApp.Models.InventoryItem");

                    b.Property<int?>("SerialNumberId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("HardwareItem");
                });

            modelBuilder.Entity("CateringApp.Models.Ingredient", b =>
                {
                    b.HasBaseType("CateringApp.Models.InventoryItem");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Ingredient");
                });

            modelBuilder.Entity("CateringApp.Models.Item", b =>
                {
                    b.HasOne("CateringApp.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CateringApp.Models.ItemClient", b =>
                {
                    b.HasOne("CateringApp.Models.Client", "Client")
                        .WithMany("ItemClients")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CateringApp.Models.Item", "Item")
                        .WithMany("ItemClients")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("CateringApp.Models.SerialNumber", b =>
                {
                    b.HasOne("CateringApp.Models.HardwareItem", "HardwareItem")
                        .WithOne("SerialNumber")
                        .HasForeignKey("CateringApp.Models.SerialNumber", "HardwareItemId");

                    b.Navigation("HardwareItem");
                });

            modelBuilder.Entity("CateringApp.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CateringApp.Models.Client", b =>
                {
                    b.Navigation("ItemClients");
                });

            modelBuilder.Entity("CateringApp.Models.Item", b =>
                {
                    b.Navigation("ItemClients");
                });

            modelBuilder.Entity("CateringApp.Models.HardwareItem", b =>
                {
                    b.Navigation("SerialNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
